language: android

android:
    components:
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
    licenses:
        - android-sdk-license-5be876d5

after_success:
    - .buildscript/deploy_snapshot.sh

env:
    global:
        - secure: "bKLqz3uHaXkdSlJ0Fr1rWUq3r6JWMad84rtc1UmBWGbIh5++5/QVBN89HfMdNQTUiPSUGuNbNlCRtjs+WCfqsuN0QzbzfGFV3Ih1ZxRmnqAhiWCwPwm2rqtYVQ21OjqCImsj+XLX/WnsFahFj8yzVpdQxVk1pv7ydujp+KDZWWyklQKJr5rz6WHIJ0pscL1mmWUm5Eu0meC8nRrTHkW8hK4DiR+XaegmSeO+LYAmv/ZDwFgMkHXSz039luJCmp13ML/J+yQ5OJ4Xmalv/c0q26M+9GrSV7QBPLwHDKOO5MSV2Gom250TVsSdzPeUqF3WXqCXrkpcT/Jp2oeBagHPN0jysrtB3UtzDxWCHPJCynGJEyP/2ro1jMdMUh1SqOFwPw2Ueq1xGdNaMSXUlrf6ahXQAup/F6n0PFUbj1MUqCqswWPb1D9IgG8MgHp9Qat1T9EcFdcHEmWWB4fnkaokFoRaCpJctlQIHIKisRlV/W0OqCJPE+SopOR2IZJ6lcZWHnB5eruVHy1xtZJTz6N5D0XTErJQJKWi8Zk29j/l2iynFC/1zYkMw5j/oPxUmR04bN1VJyetHZAnVkDe/sEbwr3D/lZdwNgPLT2tOj8OdAkGTL41F1Nge0yhuLEvhuBIJChUn2U/3uuGPn3JdQmym8TV3DI1QCfZ1Nu1+zHaSP8="
        - secure: "MlRRro2NTKCu1gG3AiuUIK1jF7zURmbxXUrmUO/jJUNSF6Shgype+dX+sFuJQvOUgq4Q1nzNGhMdL39oV6RqLqtPovt+ATbrsgGowZe0i2TkripuW/BCICJqixy1EJzqOw15EIm7JOG7asYCJX8m95pa+k71ZDEXNEPzeSes7OYDiHBSsnu6u1kdLIsMu+Ajl3dTRHbUbcpFGKKX1e7kT7GjuBRCVqNnm3JuneHlf0UxGrbNtFNojrhVBxRKo8dZHkllRk/mlEOzAP5Frx4keiDnYMs7vb7QSH3xK+RBifRaSylWnt1SyOuPLrFXRf5nP7QynyHJdE8XaaaUWxZvqme6cvRspoHabOESbVwDtgTeHN0nh4/028UPH0neGJfDTh1FbPWjsxXOmocyg3OfDSA0TtEFzjW/GzWb0lRUPv8pGxvJ2KyPUYFRDBAyOhH5LJNAcYTiON5dBU8qt/5iyoVngiXpZUdJnSXBU7/UYwU53SbQAzVC7wnXQtwcHdM8js+VwvAnyisr7eLkBvEMPtDmFOrP7+6ZqYKFJUYaHwhGxPQMwfmmlwHKLYUji+cK3TF+0EIVbMlbH7GdD2+zYANUy5XdYGHLxULLTZ4R/bTozzvticTpCe83FerqOLr2yIJSr/vmGLISFiXiuQljcxiwKaTCVudHKUAwfeXpvJ8="

cache:
    directories:
        - $HOME/.m2

script: ./gradlew check
